metakgp/iqps-go

- backend/main.go
- frontend/src/components/SearchResults.tsx
- frontend/src/components/searchForm.tsx
> Bug Fixes and No Results Message

- frontend/src/components/SearchResults.tsx
- Added an option to sort by course name or year.
- Added an option to change sorting order: ascending / descending.
> Sort By and Sort Order Options

- frontend/src/components/SearchResults.tsx
- frontend/src/styles/styles.scss
- Replaced `_` with ` ` in the file names.
- Made stuff responsive.
- Put year in the first column of the table.
> Betterest Frontend

- frontend/package.json
- frontend/pnpm-lock.yaml
- frontend/src/App.tsx
> feat: i am watching

- frontend/src/App.tsx
- frontend/src/index.tsx
> fix: watcher position rectified

- backend/main.go
Whoever first approve, please merge, don't wait for others. Thanks.
> Migrate Allowed Origins to qp.MetaKGP.org

- frontend/src/components/SearchForm.tsx
- frontend/src/components/SearchResults.tsx
- frontend/src/styles/styles.scss
- If the results are filtered by year, the sorting defaults to ascending order by course name
- If a new query is searched, the filter and sorting do not reset to default
- Error message for no results found is styled better
> QoL Frontend Changes

- frontend/src/components/SearchResults.tsx
- frontend/src/styles/styles.scss
- Responsive
- Combined "endsem" and the download button to save space
> Responsive and Better Button

- frontend/src/components/SearchResults.tsx
- Years in the filter are sorted
> fix: sort filter years

- frontend/src/components/SearchForm.tsx
- frontend/src/styles/styles.scss
- Added the query parameters to the URL
- URL link is shareable
- Added a button to copy a link to the results
> Query in the URL

- frontend/package.json
- frontend/pnpm-lock.yaml
- frontend/src/App.tsx
- frontend/src/components/SearchForm.tsx
- frontend/src/components/SearchResults.tsx
- frontend/src/styles/styles.scss
- frontend/src/utils/copyLink.ts
- Popup when copying link
- Endsem and midsem as tags (autumn/spring tags upcoming)
- Both download and copy button for pdfs
> Beautiful Frontend Design?

- frontend/src/styles/styles.scss
- frontend/src/utils/copyLink.ts
* Hardware:
* Toolchain:
* SDK:
> feat: use toast.promise and chirag's styling

- frontend/src/components/SearchResults.tsx
* Hardware:
* Toolchain:
* SDK:
> fix: do not show tag if not present

- frontend/src/components/SearchResults.tsx
* Hardware:
* Toolchain:
* SDK:
> feat: new icons, bigger icons

- backend/main.go
* Hardware:
* Toolchain:
* SDK:
> feat: not having .env is not a fatal error

- backend/docker-compose.yaml
* Hardware:
* Toolchain:
* SDK:
> feat: password daal diya

- backend/main.go
- frontend/src/pages/UploadPage.tsx
* Hardware:
* Toolchain:
* SDK:
> Upload endpoint

- frontend/src/utils/autofillData.ts
* Hardware:
* Toolchain:
* SDK:
> feat: use dashes instead of $

- backend/metaploy/iqps.metaploy.conf
- frontend/src/pages/UploadPage.tsx
* Hardware:
* Toolchain:
* SDK:
> feat: show toast on error

- backend/.env.template
- backend/docker-compose.yaml
- backend/main.go
* Hardware:
* Toolchain:
* SDK:
> fix: isse duniya ki saari dikkate thik hojani chahiye

- backend/main.go
* Hardware:
* Toolchain:
* SDK:
> Trust me bro

- backend/main.go
* Hardware:
* Toolchain:
* SDK:
> fix: last try to fix that stupid url

- README.md
- backend/docker-compose.dev.yaml
Added development docker compose to spin up a PostgreSQL database for the Go backend to connect to.
* Hardware:
* Toolchain:
* SDK:
> Added dev docker compose for dev database

- frontend/src/components/AuthProvider.tsx
- frontend/src/index.tsx
- frontend/src/pages/OAuth.tsx
This PR adds OAuth functionality to the frontend.
Fixes #62
> OAuth Frontend

- backend/go.mod
- backend/go.sum
- backend/main.go
Fixes the build issue due to missing deps.
Check : [Build Failed](https://github.com/metakgp/iqps-go/actions/runs/10027509377/job/27713282423)
> Fixes iqps build issue

- backend/main.go
* Hardware:
* Toolchain:
* SDK:
> Update Oauth to POST endpoint

- crawler/crawler.go
> Sanitize url

- backend/main.go
Admin Dashboard Endpoints - List Question Papers (Partially Fixed #79)
> list Unapproved Question Papers

- backend/src/routing/handlers.rs
Fixes a bug due to which admin approval did not work properly.
> fix: commit transaction if file paths are same

- frontend/src/pages/TrashPage.tsx
- frontend/src/pages/styles/trash_page.scss
- Fixed some styling
- the pdf links actually work now
- don't show pill if no info
Tested code ✅
> Fixes to trash page

- README.md
> Add myself as a maintainer
